version: '3.4'

services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - orionsoft
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.host:3306/soho?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Bogota

networks:
  unabnetwork:
    name: unabnetwork
    driver: bridge
  orionsoft:
    name: orionsoft
    driver: bridge