version: '3.4'

services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - unabnetwork

networks:
  unabnetwork:
    name: unabnetwork
    driver: bridge